
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: e-verification_development
  username: root
  password: scorp

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: e-verification_test
  username: root
  password: scorp

production:
  adapter: mysql2
  database: e-verification_production
  username: root
  password: scorp

